### ISSUE TITLE
Re-specify the architecture of the client

### ISSUE THREAD

**Issue by korthout** [INAETICS/AILS_Demonstrator#1]
The client architecture is currently build on the concept of requesting a locatee's (i.e. user who's location is being requested) Wi-Fi profile and then using it to find its location. The server has changes to a new format: user's continuously send their Wi-Fi profiles, which are continuously used for locating the user. This location info is then stored and can be requested at any given moment. 

Changes to the server architecture require similar changes to the client architecture. Therefore, these changes have to be reflected in the client architecture.

**Comment by ghost** [comment]
Redefined the client api. Changed the AnonUser to simply a User because we don't need the mac address information about a User. The INAETICS architecture enables us to directly contact a user if needed without needing extra information (such as a mac address). In order to be more consistent, we also added the accuracy information of a User into its model. In order to keep privacy a main issue, we changed the AnonUserWiFiProfile model to UUIDWifiProfile. For other changes, please refer to the architecture in the google drive.

**Comment by korthout** [comment]
Still missing a diagram of the client architecture, but finished otherwise. This diagram will soon be uploaded.

**Comment by korthout** [comment]
Still missing a diagram of the client architecture, but finished otherwise. This diagram will soon be uploaded.
